cd tests/

make test--accept.exe
make test-auth-basic.exe
make test-auth-digest.exe
make test-bad-chunk.exe
make test-base.exe
make test-chunked.exe
make test-c-r.exe
make test-cut-dirs.exe
make test-directory-clash.exe
make test--follow-tags.exe
make test-idn-cmd.exe
make test-idn-meta.exe
make test-idn-robots.exe
make test-i-http.exe
make test-i-https.exe
make test-iri.exe
make test-iri-forced-remote.exe
make test-iri-list.exe
make test-iri-percent.exe
make test-iri-subdir.exe
make test-k.exe
make test-metalink.exe
make test-meta-robots.exe
make test-np.exe
make test--page-requisites.exe
make test-parse-css.exe
make test-parse-html-css.exe
make test-parse-rss.exe
make test-plugin.exe
make test-redirection.exe
make test-restrict-ascii.exe
make test-robots.exe
make test--spider-r.exe
make test-wget-1.exe

wine test--accept.exe
wine test-auth-basic.exe
wine test-auth-digest.exe
wine test-bad-chunk.exe
wine test-base.exe
wine test-chunked.exe
wine test-c-r.exe
wine test-cut-dirs.exe
wine test-directory-clash.exe
wine test--follow-tags.exe
wine test-idn-cmd.exe
wine test-idn-meta.exe
wine test-idn-robots.exe
wine test-i-http.exe
wine test-i-https.exe
wine test-iri.exe
wine test-iri-forced-remote.exe
wine test-iri-list.exe
wine test-iri-percent.exe
wine test-iri-subdir.exe
wine test-k.exe
wine test-metalink.exe
wine test-meta-robots.exe
wine test-np.exe
wine test--page-requisites.exe
wine test-parse-css.exe
wine test-parse-html-css.exe
wine test-parse-rss.exe
wine test-plugin.exe
wine test-redirection.exe
wine test-restrict-ascii.exe
wine test-robots.exe
wine test--spider-r.exe
wine test-wget-1.exe
